spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:booking_app_dev}
    username: ${DB_USERNAME:booking_user}
    password: ${DB_PASSWORD:booking_password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
